name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Type-check Proofs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Elan & Lean 4
        uses: leanprover/lean-action@v1

      - name: Build Project Workspace
        run: |
          lake build
